/**
 * Helpers for race-safe question_number generation.
 *
 * question_number is auto-generated by reading the current max for a
 * (category, sub_category) and incrementing it. Two concurrent POSTs would read the
 * same max and compute the same number, violating UNIQUE(category, question_number).
 * The POST handler serializes them with a transaction-scoped advisory lock keyed on
 * this string, so only one request generates a number for a given sub-category at a time.
 */
import { compareQuestionNumber } from "@/lib/question-sort";

/**
 * Build the deterministic, collision-free key passed to `pg_advisory_xact_lock(hashtext(...))`.
 * Length-prefixing the category prevents `("A|B","C")` and `("A","B|C")` from colliding.
 */
export function questionNumberLockArg(category: string, subCategory: string): string {
  return `question_number:${category.length}:${category}|${subCategory}`;
}

/**
 * Given the existing question numbers in a sub-category, return the next number by
 * incrementing the minor part of the numeric maximum. Sorting numerically (not
 * lexicographically) is what prevents regenerating an existing number once a
 * sub-category passes 9 questions (e.g. max of ["2.9","2.10"] must be "2.10" → "2.11").
 */
export function nextMinorNumber(existingNumbers: string[]): string {
  const max = [...existingNumbers].sort(compareQuestionNumber).at(-1)!;
  const [major, minor] = max.split(".");
  return `${major}.${parseInt(minor || "0", 10) + 1}`;
}
